### ISSUE TITLE
Write SSS data

### ISSUE THREAD

**Issue by rbirkelbach** [andrie/sss#8]
Hello,

would it be possible to implement a function that writes a triple-s data file?

Best and thanks,
Robert

**Comment by andrie** [comment]
I'm sure it's possible.  Do you want to contribute some code?

**Comment by rbirkelbach** [comment]
Unfortunately, I do not know enough about sss files (ie. I barely know anything about sss). The company I work for evaluates whether it's worth it switching to R from SPSS and this is the only task I was unable to figure out how to do so with R that they want to do. Your R library was the only library I found that can handle triple-s files at all.

**Comment by andrie** [comment]
Well, if this is the only thing that prevents them from switching to R, then there is bound to be a positive business case to get a contractor to do this work.

I don't think it's particularly difficult to do.  The `sss` standard simply defines a description of the columns as XML output.

This package already does the reverse operation, as you pointed out.  So it should be a fairly mechanical task. You will need someone who knows a little about R and a little about XML.
